Add docker
greblovp/java-shareit pull request #4
Opened 2023-07-05 21:38 UTC by greblovp

2023-07-06 18:15 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь две небольшие рекомендации

2023-07-06 18:15 UTC, mikita95 commented on gateway/Dockerfile
> +FROM amazoncorretto:11
Можно ещё передать параметры java, например, для настройки памяти, а также указать tmp директорию:
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]

2023-07-06 18:15 UTC, mikita95 commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Слишком большой оступ, должно быть 4 пробела

2023-07-07 12:38 UTC, greblovp commented on gateway/Dockerfile
> +FROM amazoncorretto:11
добавил в Dockerfile. В docker-compose вынес присвоение значения переменной окружения JAVA_OPTS

2023-07-09 14:50 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-07-10 18:09 UTC, merged